{% set version = "0.7.1" %}

package:
  name: rav1e
  version: {{ version }}

source:
  url: https://github.com/xiph/rav1e/archive/refs/tags/v{{ version }}.tar.gz
  sha256: da7ae0df2b608e539de5d443c096e109442cdfa6c5e9b4014361211cf61d030c
  patches:
    # I'm not sure why it is failing on building git_version on ppc64le only
    # It seems that an mtune flag is being passed through
    # but in reality, we aren't using the git source, so this "feature"
    # is mostly returning the git describe --always
    # of this feedstock which likely isn't what the library authors intended
    # removing this dependency has the side effect of allowing the builds to pass
    # on ppc64le
    - no_git_version.patch

build:
  number: 3
  run_exports:
    # It seems that they export a so with .0, so I'm going to wish for the best
    # But there is no gurantee so lets tighten this up a little bit
    - {{ pin_subpackage('rav1e', max_pin='x.x') }}
  has_prefix_files:
    - Library/lib/pkgconfig/rav1e.pc  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-c
    - nasm
    - pkg-config                         # [unix]

test:
  requires:
    - cmake
    - ninja
    - pkg-config
  files:
    - CMakeLists.txt
  commands:
    # Do not include statically linked 60MB binary....
    # - rav1e --version
    - test ! -f ${PREFIX}/bin/rav1e                             # [unix]
    - if exist %LIBRARY_PREFIX%\\bin\\rav1e.exe exit 1          # [win]
    - test -f ${PREFIX}/lib/librav1e${SHLIB_EXT}                # [unix]
    - test -f ${PREFIX}/lib/librav1e.so.0.7                     # [linux]
    - test -f ${PREFIX}/lib/librav1e.0.7.dynlib                 # [osx]
    - if not exist %LIBRARY_PREFIX%\\bin\\rav1e.dll exit 1      # [win]
    - if not exist %LIBRARY_PREFIX%\\lib\\rav1e.dll.lib exit 1  # [win]
    - cmake . -GNinja

about:
  home: https://github.com/xiph/rav1e
  summary: The fastest and safest AV1 encoder.
  description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use
    cases, though in its current form it is most suitable for cases where
    libaom (the reference encoder) is too slow.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - hmaarrfk
